### ISSUE TITLE
Ignore all class-string type issues in Scrutinizer

### ISSUE THREAD

**Issue by szepeviktor** [sj-i/typist#4]
@sj-i Issue: https://scrutinizer-ci.com/g/sj-i/typist/issues/master/files/src/Typist/ClassEnforcer.php?orderField=path&order=asc&honorSelectedPaths=0

Docs: https://scrutinizer-ci.com/docs/reviews/filtering_issues_and_false_positives

Thanks.

**Comment by sj-i** [comment]
Done, thanks!!!

**Comment by szepeviktor** [comment]
![kép](https://user-images.githubusercontent.com/952007/88566633-954ec400-d036-11ea-9dd1-8db4e99b9c7c.png)
